language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_567ed4364646_key -iv $encrypted_567ed4364646_iv -in src/main/resources/application.properties.enc -out src/main/resources/application.properties -d

